new TSD pthread API
janjust/ompi pull request #4
Opened 2020-07-13 15:19 UTC by janjust

2020-07-13 15:34 UTC, artpol84 requested changes

2020-07-13 15:34 UTC, artpol84 commented on opal/mca/threads/pthreads/threads_pthreads_module.c
> +static void opal_tsd_tracked_key_destructor_wrapper(void *arg) {
```suggestion
static void _tracked_destructor(void *arg) {
```

2020-07-13 15:34 UTC, artpol84 commented on opal/mca/threads/pthreads/threads_pthreads_tsd.h
> +
Why is this in the pthread_tsd and not in tsd.h?

This API should fully rely on opal_tsd_key_t and thus not be thread implementation-specific.

2020-07-13 15:34 UTC, artpol84 commented on opal/mca/threads/tsd.h
> +        opal_tsd_tracked_key_t *key, opal_tsd_destructor_t destructor);
```suggestion
OPAL_DECLSPEC int opal_tsd_tracked_key_set(opal_tsd_tracked_key_t *key, void *p);
OPAL_DECLSPEC int opal_tsd_tracked_key_get(opal_tsd_tracked_key_t *key, void **p);
OPAL_DECLSPEC void opal_tsd_tracked_key_destructor(opal_tsd_tracked_key_t *key,
         opal_tsd_destructor_t destructor);
```

2020-07-13 15:34 UTC, artpol84 commented on opal/mca/threads/pthreads/threads_pthreads_module.c
> +OBJ_CLASS_INSTANCE(opal_tsd_data_list_t, opal_list_item_t, NULL, NULL);
```suggestion
OBJ_CLASS_INSTANCE(opal_tsd_list_item_t, opal_list_item_t, NULL, NULL);
```

2020-07-13 15:34 UTC, artpol84 commented on opal/mca/threads/pthreads/threads_pthreads_module.c
> +    opal_tsd_data_list_t *tsd = pthread_getspecific(key->key);
wrong
Use opal_tsd_key_set()

2020-07-13 15:34 UTC, artpol84 commented on opal/mca/threads/pthreads/threads_pthreads_tsd.h
> +    opal_tsd_key_t key;
threading implementation agnostic!!!

2020-07-13 15:34 UTC, artpol84 commented on opal/mca/threads/pthreads/threads_pthreads_module.c
> +int opal_tsd_tracked_key_getspecific(opal_tsd_tracked_key_t *key, void **p)
No "[set|get]specific", just [set|get]

2020-07-13 21:49 UTC, artpol84 commented on opal/mca/threads/tsd.h
> +};
```suggestion
struct opal_tsd_tracked_key_s {
    opal_object_t super;
    opal_tsd_key_t key;
    opal_mutex_t mutex;
    opal_list_t tsd_list;
    void (*user_destructor)(void *);
} opal_tsd_tracked_key_t;
```

2020-07-13 21:49 UTC, artpol84 commented on opal/mca/threads/tsd.h
> +OPAL_DECLSPEC int opal_tsd_tracked_key_get(opal_tsd_tracked_key_t *key, void **p);
inline

2020-07-13 21:50 UTC, artpol84 commented on opal/mca/threads/tsd.h
> +OBJ_CLASS_DECLARATION(opal_tsd_list_item_t);
```suggestion
```
Lets move this to the base.c. It doesn't need to be exposed

2020-07-13 21:51 UTC, artpol84 commented on opal/mca/threads/pthreads/threads_pthreads_tsd.h
> +typedef struct _opal_tsd_tracked_key_t opal_tsd_tracked_key_t;
```suggestion
```

2020-07-13 21:51 UTC, artpol84 commented on opal/mca/threads/base/Makefile.am
> +		base/tsd.c
```suggestion
        base/tsd.c
```

2020-07-13 21:52 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +    if (NULL == arg) {
```suggestion
    opal_tsd_list_item_t *tsd = NULL;
    opal_tsd_tracked_key_t *key = NULL;
    if (NULL == arg) {
```

2020-07-13 21:53 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +
```suggestion
    tsd = (opal_tsd_list_item_t *)arg;
    key = tsd->tracked_key;
```

2020-07-13 21:54 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +
```suggestion
```

2020-07-13 21:54 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +    pthread_key_create(&key->key, &_tracked_destructor);
```suggestion
    pthread_key_create(&key->key, _tracked_destructor);
```

2020-07-13 21:54 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +
```suggestion
```

2020-07-13 21:55 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +
```suggestion
```

2020-07-13 21:55 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +
```suggestion
```

2020-07-13 21:55 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +    opal_mutex_lock(&key->mutex);
```suggestion
```

2020-07-13 21:56 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +    opal_mutex_unlock(&key->mutex);
```suggestion
```

2020-07-13 21:56 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +    opal_mutex_lock(&key->mutex);
Its already assumed that no other thread can take the lock.
Otherwise it might get try to do that after mutex destruction

2020-07-13 21:58 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +}
```suggestion
```

Move as inline to the tsd.h

2020-07-13 22:42 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +    opal_tsd_tracked_key_t *key = NULL;
is it duplicated?

2020-07-13 22:45 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +    opal_tsd_tracked_key_t *key = NULL;
```suggestion

```

2020-07-13 22:47 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +    opal_tsd_getspecific(key->key, (void **)&tsd);
```suggestion
    opal_tsd_get(key->key, (void **)&tsd); 
```

2020-07-13 22:47 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +    opal_tsd_getspecific(key->key, (void **)&tsd);
Remember, we agreed to get rid of "specific" in opal API

2020-07-13 22:53 UTC, artpol84 commented on opal/mca/threads/base/tsd.c
> +    return opal_tsd_setspecific(key->key, (void *)tsd);
```suggestion
    return opal_tsd_set(key->key, (void *)tsd);
```

2020-07-13 22:53 UTC, artpol84 commented on opal/mca/threads/tsd.h
> +    opal_tsd_getspecific(key->key, (void **)&tsd);
```suggestion
    opal_tsd_get(key->key, (void **)&tsd); 
```

2020-07-13 22:54 UTC, artpol84 commented
Looks good now!

2020-07-14 00:45 UTC, janjust commented on opal/mca/threads/base/tsd.c
> +    opal_tsd_tracked_key_t *key = NULL;
yes - removed

2020-07-14 03:34 UTC, closed without merging